minimum_pre_commit_version: 4.0.0
exclude: |
  (?x)^(
    3rdparty/|
    test/3rdparty/|
    build/|
    test/build/
  )

default_stages: [pre-commit]
ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://gitcode.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [manual]
      - id: end-of-file-fixer
        stages: [manual]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://gitcode.com/pre-commit-clang/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
        args: [--style=file, --dry-run, --Werror]

  - repo: local
    hooks:
      - id: run-build
        name: Run release build
        entry: bash build.sh -t release
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

      - id: run-build-test
        name: Build unit tests
        entry: bash -c 'cd test && sh run_dt.sh --skip-run-tests'
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

      - id: clang-tidy
        name: Run clang-tidy for source files
        entry: clang-tidy
        language: system
        files: ^src/.*\.(h|c|cpp)$
        args: [-p=build/debug]
        stages: [manual]

      - id: clang-tidy-test
        name: Run clang-tidy for test files
        entry: clang-tidy
        language: system
        files: ^test/.*\.(h|c|cpp)$
        args: [-p=test/build]
        stages: [manual]
