/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

 * ubs-mem is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *      http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef MESSAGE_OP_H
#define MESSAGE_OP_H

#include <cstdint>
enum RmMemOpCodeIpc : uint16_t {
    MEM_OP_SERVER_BEGIN = 0,
    // 内存借用
    IPC_FREE_RACKMEM,
    IPC_MALLOC_MEMORY,
    IPC_MALLOC_MEMORY_LOC,
    IPC_CHECK_MEMORY_LEASE,

    // 内存共享
    IPC_RACKMEMSHM_LOOKUP_SHAREREGIONS,
    IPC_RACKMEMSHM_LOOKUP_REGIONINFO,
    IPC_RACKMEMSHM_CREATE,
    IPC_RACKMEMSHM_CREATE_WITH_PROVIDER,
    IPC_RACKMEMSHM_MMAP,
    IPC_RACKMEMSHM_UNMMAP,
    IPC_RACKMEMSHM_DELETE,
    IPC_RACKMEMSHM_QUERY_MEM_FAULT_STATUS,
    IPC_CHECK_SHARE_MEMORY,

    // 资源域
    IPC_REGION_LOOKUP_REGION_LIST,
    IPC_REGION_CREATE_REGION,
    IPC_REGION_LOOKUP_REGION,
    IPC_REGION_DESTROY_REGION,

    // 锁操作
    IPC_RACKMEMSHM_WRITELOCK,
    IPC_RACKMEMSHM_READLOCK,
    IPC_RACKMEMSHM_UNLOCK,

    IPC_QUERY_CLUSTERINFO,
    IPC_FORCE_FREE_CACHED_MEMORY,
    IPC_QUERY_CACHED_MEMORY,

    IPC_RACKMEMSHM_LOOKUP_LIST,
    IPC_RACKMEMSHM_LOOKUP,
    IPC_RACKMEMSHM_ATTACH,
    IPC_RACKMEMSHM_DETACH,

    IPC_RACKMEMSHM_QUERY_DLOCK_STATUS,

    // 选主模块
    IPC_RACKMEMSHM_QUERY_NODE,
    // 查询当前节点id
    IPC_RACKMEMSHM_QUERY_SLOT_ID,
};

enum RmMemOpCodeRpc : uint16_t {
    RPC_AGENT_QUERY_NODE_INFO = 100,

    // DLOCK
    RPC_DLOCK_CLIENT_REINIT,
    RPC_LOCK,
    RPC_UNLOCK,

    // 选主数据传输
    RPC_PING_NODE_INFO,
    RPC_JOIN_NODE_INFO,
    RPC_MASTER_ELECTED_NODE_INFO,
    RPC_SEND_ELECTED_MASTER_INFO,
    RPC_VOTE_NODE_INFO,
    RPC_BROADCAST_NODE_INFO,
};

#endif  // MESSAGE_OP_H