/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

 * ubs-mem is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *      http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#ifndef UBSM_MEM_FABRIC_PTRACER_CONST_H
#define UBSM_MEM_FABRIC_PTRACER_CONST_H

#include "ptracer.h"

enum UBSM_MEM_MOD {
    TP_UBSM_START = PTRACER_ID(0, 0U),
    TP_UBSM_MEM_SHM_CREATE,

    TP_UBSM_GET_HANDLER,
    TP_UBSM_HCOM_CALL,
    TP_UBSM_IPC_CALL,

    TP_UBEM_IPC_HANDLER_MALLOC,
    TP_UBSM_MALLOC,
    TP_UBSM_MALLOC_LOC,
    TP_UBSM_MALLOC_IPC_REQUEST,
    TP_UBSM_MALLOC_LOC_IPC_REQUEST,
    TP_UBSM_MALLOC_NUMA_MAP,
    TP_UBSM_MALLOC_NUMA_BIND,
    TP_UBSM_MALLOC_FD_MAP,
    TP_UBSM_MALLOC_FD_OPEN,
    TP_UBSM_MALLOC_FD_BIND,

    TP_UBEM_IPC_HANDLER_FREE,
    TP_UBSM_FREE,
    TP_UBSM_FREE_FD_UNMMAP,
    TP_UBSM_FREE_FD_CLOSE,
    TP_UBSM_FREE_NUMA_UNMMAP,
    TP_UBSM_FREE_IPC_REQUEST,

    TP_UBSM_CLOSE,

    TP_UBEM_IPC_HANDLER_CREATE_SHMEM,
    TP_UBEM_IPC_HANDLER_CREATE_WITH_PROVIDER_SHMEM,
    TP_UBSM_SHM_CREATE,
    TP_UBSM_SHM_CREATE_WITH_PROVIDER,
    TP_UBSM_SHM_CREATE_IPC_REQUEST,
    TP_UBSM_SHM_CREATE_WITH_PROVIDER_IPC_REQUEST,
    TP_UBSE_IS_BOUND_NUMA,
    TP_UBSE_MEM_SHM_CREATE,
    TP_UBSE_MEM_SHM_CREATE_WITH_PROVIDER,
    TP_UBEM_GET_REGION,
    TP_UBSE_MEM_SHM_CREATE_WITH_AFFINITY,

    TP_UBEM_IPC_HANDLER_MAP,
    TP_UBSM_SHM_MAP,
    TP_UBSM_SHM_MAP_IPC_REQUEST,
    TP_UBSM_SHM_MMAP_ADDR,
    TP_UBSM_SHM_BIND_ADDR,
    TP_UBSM_GET_SHARED_MEMORY_INFO,
    TP_UBSM_REUSE_SHARED_MEMORY,
    TP_UBSE_GET_SHARED_MEMORY,
    TP_UBSE_ATTACH_SHARED_MEMORY,

    TP_UBEM_IPC_HANDLER_UNMMAP,
    TP_UBSM_SHM_UNMAP,
    TP_UBSM_UNMAP_ADDR,
    TP_UBSM_CLOSE_FD,
    TP_UBSM_SHM_UNMAP_IPC_UNMMAP,
    TP_UBSE_SHM_DATECH_SHARED_MEMORY,

    TP_UBEM_IPC_HANDLER_DELETE,
    TP_UBSM_SHM_DELETE,
    TP_UBSM_SHM_DELETE_IPC_REQUEST,
    TP_UBSE_DELETE_SHARED_MEMORY,

    TP_UBSM_SHM_ATTACH,
    TP_UBSM_SHM_ATTACH_IPC_REQUEST,

    TP_UBSM_SHM_DETACH,
    TP_UBSM_SHM_DETACH_IPC_REQEUST,

    TP_UBSM_SET_SHMEM_OWERSHIP,
    TP_USBM_OBMM_SET_OWERSHIP,

    TP_UBSM_GET_LOCAL_NODE_ID,
    TP_UBSM_SET_PERMISSION,

    TP_UBSM_REUSE_MEM,
    TP_UBSM_LEASE_MALLOC,
    TP_UBSM_LEASE_MALLOC_WITH_LOC,
    TP_UBSM_CREATE_NUMA_MEM,
    TP_UBSM_CREATE_NUMA_MEM_WITH_LOC,
    TP_UBSM_CREATE_FD_MEM,
    TP_UBSM_ADD_USED_MEM,
    TP_UBSM_CREATE_FD_MEM_WITH_LOC,

    TP_UBSM_DELETE_REUSE_MEM,
    TP_UBSM_LEASE_FREE,
    TP_UBSM_DELETE_NUMA_MEM,
    TP_UBSM_DELETE_FD_MEM,

    TP_UBSM_LOOKUP_REGIONS,
    TP_UBSM_LOOKUP_REGIONS_IPC_REQUEST,
    TP_UBSM_GET_NODE_LIST,

    TP_UBSM_LOOKUP_REGION,
    TP_UBSM_LOOKUP_REGION_DEFAULT_IPC_REQUEST,
    TP_UBSM_LOOKUP_REGION_IPC_REQUEST,

    TP_UBSM_CREATE_REGIONS,
    TP_UBSM_CREATE_REGIONS_IPC_REQUEST,

    TP_UBSM_DESTORY_REGION,
    TP_UBSM_DESTORY_REGION_IPC_REQUEST,

    TP_UBSM_WRITE_LOCK,
    TP_UBSM_WRITE_LOCK_IPC_REQUEST,
    TP_UBSM_WRITE_LOCK_SET_OWERSHIP,

    TP_UBSM_READ_LOCK,
    TP_UBSM_READ_LOCK_IPC_REQUEST,
    TP_UBSM_READ_LOCK_SET_OWNERSHIP,

    TP_UBSM_LOCK_RPC_CONNECT,
    TP_UBSM_LOCK_RPC_SEND_MSG,
    TP_UBSE_LOCK_RPC_HANDLE,
    TP_UBSM_GET_LOCK,
    TP_UBSM_DLOCK_GET_LOCK,
    TP_UBSM_TRY_LOCK,
    TP_UBSM_DLOCK_TRY_LOCK,

    TP_UBSM_UNLOCK,
    TP_UBSM_UNLOCK_SET_OWNERSHIP,
    TP_UBSM_UNLOCK_IPC_REQUEST,
    TP_UBSM_UNLOCK_RPC_SEND_MSG,
    TP_UBSM_UNLOCK_RPC_HANDLE,
    TP_UBSM_DLOCK_UNLOCK,
};
namespace ock {
namespace ubsm {
namespace tracer {
class UbsmPtracer {
public:
    static int32_t Init()
    {
#if defined(DEBUG_MEM_UT) || defined(UBS_MEM_SDK_OBJECT)
        auto dumpFilePath = "/tmp";
#else
        auto dumpFilePath = "/var/log/ubsm";
#endif
        int32_t traceType = 1;
        ptracer_config_t config = {traceType, dumpFilePath};
        return ptracer_init(&config);
    }
    static void UnInit() { ptracer_uninit(); }
};
}  // namespace tracer
}  // namespace ubsm
}  // namespace ock
#endif  // UBSM_MEM_FABRIC_PTRACER_CONST_H