# the log level of ubsm server, (DEBUG, INFO, WARN, ERROR, CRITICAL)
ubsm.server.log.level = INFO
# the log file path, must be canonical path
ubsm.server.log.path = /var/log/ubsm
# log file count, min is 1, max is 50
ubsm.server.log.rotation.file.count = 10
# log file size(MB), min is 2, max is 100
ubsm.server.log.rotation.file.size = 20

# enable or disable audit log, (on, off)
ubsm.server.audit.enable = on
# audit log, the configuration item value range is the same as 'ubsm.server.log.*'
ubsm.server.audit.log.path = /var/log/ubsm
ubsm.server.audit.log.rotation.file.count = 10
ubsm.server.audit.log.rotation.file.size = 20

# CC lock
ubsm.lock.enable = off
ubsm.lock.expire.time = 300
ubsm.lock.dev.name = bonding_dev_0
ubsm.lock.dev.eid = 0
ubsm.lock.ub_token.enable = on
ubsm.lock.tls.enable = on
ubsm.lock.tls.ca.path = /path/cacert.pem
ubsm.lock.tls.crl.path = /path/crl.pem
ubsm.lock.tls.cert.path = /path/cert.pem
ubsm.lock.tls.key.path = /path/key.pem
ubsm.lock.tls.keypass.path = /path/keypass.txt

# Zen discovery
# election timeout, min is 0, max is 2000
ubsm.discovery.election.timeout = 1000
# min nodes, min is 0, max is 30
ubsm.discovery.min.nodes = 0

ubsm.server.rpc.local.ipseg = 127.0.0.1:7201
ubsm.server.rpc.remote.ipseg = 127.0.0.1:7301
# tls options
ubsm.server.tls.enable = on
ubsm.server.tls.ciphersuits = aes_gcm_128
ubsm.server.tls.ca.path = /path/cacert.pem
ubsm.server.tls.crl.path = /path/crl.pem
ubsm.server.tls.cert.path = /path/cert.pem
ubsm.server.tls.key.path = /path/key.pem
ubsm.server.tls.keypass.path = /path/keypass.txt


# max is 256, default 128
ubsm.hcom.max.connect.num = 128
# enable or disable memory lease cache, (on, off)
ubsm.server.lease.cache.enable = off
# enable performance statistics, (on off)
ubsm.performance.statistics.enable = off