SET(CPACK_PACKAGE_VENDOR "Huawei Technologies Co., Ltd.")
SET(CPACK_PACKAGE_NAME "ockdaemon")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OCK Daemon")
SET(CPACK_PACKAGE_CONTACT "")

SET(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})

SET(OS_DISTRIBUTION ${CMAKE_SYSTEM_PROCESSOR}_${CMAKE_SYSTEM_NAME})
STRING(TIMESTAMP CPACK_TIME_STR "%Y%m%d" UTC)

STRING(TOLOWER ${CPACK_PACKAGE_NAME} PACKAGE_VER_NAME)
SET(CPACK_PACKAGE_FILE_NAME ${PACKAGE_VER_NAME}-${CMAKE_BUILD_TYPE})

SET(CPACK_PACKAGING_INSTALL_PREFIX "/${CPACK_PACKAGE_NAME}")
SET(CPACK_INCLUDE_TOPLEVEL_DIRECTORY FALSE)

SET(CPACK_GENERATOR "TGZ")

INCLUDE(CPack)

set(CMAKE_ARC linux-aarch64)

SET(DAEMON_INSTALL_EXE_PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE)

SET(DEAMON_INSTALL_LIB_PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE)

SET(DAEMON_INSTALL_DOC_PERMISSIONS
        OWNER_READ OWNER_WRITE
        GROUP_READ
        WORLD_READ)

SET(DAEMON_RUNTIME_DESTINATION ock/bin PARENT_SCOPE)
SET(DAEMON_LIBRARY_DESTINATION ock/lib PARENT_SCOPE)
SET(DAEMON_COMMON_LIBRARY_DESTINATION ${DAEMON_LIBRARY_DESTINATION}/common)
SET(DAEMON_ARCHIVE_DESTINATION ock/etc)
SET(DAEMON_LOG_DESTINATION ${PROJECT_BINARY_DIR}/logs)
SET(DAEMON_WORK_DESTINATION ${PROJECT_BINARY_DIR}/work/pids)
SET(DAEMON_CONF ock/conf)

FILE(MAKE_DIRECTORY ${DAEMON_LOG_DESTINATION})
FILE(MAKE_DIRECTORY ${DAEMON_WORK_DESTINATION})
install(DIRECTORY ${DAEMON_LOG_DESTINATION} DESTINATION ${PROJECT_BINARY_DIR}
        DIRECTORY_PERMISSIONS ${DAEMON_INSTALL_DOC_PERMISSIONS}
        COMPONENT OCK_DAEMON_COMPONENT)
install(DIRECTORY ${DAEMON_WORK_DESTINATION} DESTINATION ${PROJECT_BINARY_DIR}/work
        DIRECTORY_PERMISSIONS ${DAEMON_INSTALL_DOC_PERMISSIONS}
        COMPONENT OCK_DAEMON_COMPONENT)

SET(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)
SET(CPACK_RPM_COMPONENT_INSTALL ON)

CPACK_ADD_COMPONENT(OCK_DAEMON_COMPONENT
        DISPLAY_NAME "alpha"
        DESCRIPTION "package for test"
        GROUP OCK_DAEMON)

CPACK_ADD_COMPONENT_GROUP(OCK_DAEMON)
